### ISSUE TITLE
resetting light

### ISSUE THREAD

**Issue by patrol420** [diyhue/Lights#1]
not so much an issue, wondering if possible to reset the light without re uploading firmware so i can change SSID that it connects to? using Generic RGBW light code

**Comment by mariusmotea** [comment]
you need to disable your router wifi for few seconds or start the esp8266 isolated or far  from router. This way connection will fail and it will popup again the SSID from  WiFI manager for connection setup.

**Comment by patrol420** [comment]
Thanks alot

**Comment by patrol420** [comment]
Thanks alot
