### ISSUE TITLE
Wifi Issue ESP8266 

### ISSUE THREAD

**Issue by Badn1nja** [diyhue/Lights#102]
Hi,
I've had this as an ongoing issue I've not seen it show up before on github.

I have a esp light strip but the wifi network it creates never disappeared once its connected to my wireless network its showing as ESP-70e971 and can be connected to by anyone.

Is there a way to make this go away?

**Comment by mariusmotea** [comment]
Hi,

This is an issue with new esp library. Need to declare the wifi mode in setup phase. I will create a fix for all lights soon.

**Comment by mariusmotea** [comment]
Can you please test now and confirm? I made commits for all lights.

**Comment by Badn1nja** [comment]
I will test shortly

**Comment by mariusmotea** [comment]
It is workinking as expected now?

**Comment by Badn1nja** [comment]
Yes perfect thanks for that, just had to setup Arduino on a new computer before testing
