### ISSUE TITLE
Any chance to use ESP-01S RGB led ring?

### ISSUE THREAD

**Issue by jarno83** [diyhue/Lights#105]
Hi, I have multiple of them 16 led and 8 led ones. https://www.aliexpress.com/item/4001135425711.html
I got firmware flashed to esp01s and app found the device but didn't control the leds. I used Generic_WS2812_Strip.ino.
I think it's something to do with NeoPixelBus default pin on esp8226?

Thank you :)

**Comment by Mevel** [comment]
Default Pin is the RX pin.
According to the Picture it should be Pin 7 (GPIO3)
You can edit the pin in the web Ui of your light.

https://diyprojects.io/media/2020/09/esp01-esp01s-pinout-esp8266ex.jpg



<blockquote></blockquote>

**Comment by jarno83** [comment]
Hi, I checked with tester and ESP-01S-RGB  uses GPIO2. In the preferences I don't see where I can change PIN for the neopixels. 
![Screenshot 2020-12-25 at 15 05 33](https://user-images.githubusercontent.com/607818/103135702-c05f4180-46c2-11eb-9c5b-891e5a881a60.png)
I can see where I can turn on HW buttons, but thats it.
Can I change the output pin? Or I need to do some hw modding :)

Thanks.

**Comment by Mevel** [comment]
sry my bad!
I think neopixelbus uses RX Pin per Default.
See post before.

Dont change the sketch, just upload.

make sure you have SPIFFS and "Erase whole Flash" on initial Flash.
