### ISSUE TITLE
SK9822 support

### ISSUE THREAD

**Issue by GhostR111der** [diyhue/Lights#106]
Hello! Are you going to add SK9822 strip support?

**Comment by Mevel** [comment]
As we use the neopixelbus library from [Makuna](https://github.com/Makuna/NeoPixelBus) it should be possible as the library already supports this type of LED Driver.

You can try one of the SK-XXX sketches to see what suits your needs

**Comment by mariusmotea** [comment]
https://cpldcpu.wordpress.com/2016/12/13/sk9822-a-clone-of-the-apa102/

<blockquote><img src="https://cpldcpu.files.wordpress.com/2016/12/ws9822_update.png" width="48" align="right"><div><img src="https://s1.wp.com/i/favicon.ico" height="14"> Tim's Blog</div><div><strong><a href="https://cpldcpu.wordpress.com/2016/12/13/sk9822-a-clone-of-the-apa102/">SK9822 – a clone of the APA102?</a></strong></div><div>Two years ago I took a deeper look into the APA102. Although it was more expensive than the common WS2812, and harder to come by, it had some intriguing properties. The main benefits are a timing-i…</div></blockquote>
