### ISSUE TITLE
Hue App crash on light add with Gradient_Strip_WS2812

### ISSUE THREAD

**Issue by Jimbo145** [diyhue/Lights#112]
The Hue App light setup screen crashes when trying to add the Gradient_Strip_WS2812 light.

config.json must have LCX002 entry removed before add light dialog option works again.

Hue Essentials does not detect a new light.

Android Hue App 3.48.22 (7637)
DIY Hue version #611

**Comment by mariusmotea** [comment]
Gradient Strip works only with flask branch that is currently in development.
