### ISSUE TITLE
Infinity loop esp8266 after upload the code

### ISSUE THREAD

**Issue by ngoquytuan** [diyhue/Lights#115]
Hi,
I use "esp8266 mini d1" boards and upload the Generic_WS2812_Strip.ino, Gradient_Strip_WS2812.ino with arduino and I got infinity loop esp8266 after upload the code. I changed some config ( FS..) but the esp8266 still retarting in a loop. I flash bin file with "flash_download_tool_v3.8.8" with out error on the same board. What problem happen with my upload code?
Thanks.

**Comment by mariusmotea** [comment]
Compile the code with last esp 2.x.x library. The new 3.0 library has known issues.

**Comment by ngoquytuan** [comment]
Thanks. I done it!
