### ISSUE TITLE
Wrong Sketch Used By Webtool

### ISSUE THREAD

**Issue by ryancasler** [diyhue/Lights#116]
I attempted to use the Dimmable V2 sketch but the sketch that was uploaded appears to be for a digital RGB(w) strip because the options are all wrong.  There is a pixel count and transition LEDs, both of which wouldn't be possible with a simple dimmable analog strip.

**Comment by mariusmotea** [comment]
Thanks, i will check this.

**Comment by mariusmotea** [comment]
I recompile now the firmware, hope it works as expected.
