### ISSUE TITLE
WS2812B - Custom Pixel Groupings (not dividing number of LEDs by light count)

### ISSUE THREAD

**Issue by charlescbullock** [diyhue/Lights#12]
Hey guys!

I wanted to see if anyone has already done this, before I go diving into it..

Has anybody made the sketch able to set custom groupings of LEDs with WS2812B strips?
..Where you can set several lights' pixelCount within a single ESP8266, without having to divide pixelCount by lightsCount..

For instance, a user could input these values for various sections of light..

genericLightName 1 has a Pixel Count of 16
genericLightName 2 has a Pixel Count of 16
genericLightName 3 has a Pixel Count of 78
genericLightName 4 has a Pixel Count of 28
genericLightName 5 has a Pixel Count of 40
genericLightName 6 has a Pixel Count of 20

I'm attempting to install this system throughout my kitchen, and my cabinets are different sizes.
Ideally, each cabinet has its own "light" section to control.. Allowing a user to use the hue app, and modify lighting cabinet-by-cabinet. 

I am trying to avoid having sections span more than one cabinet. 
Transition LEDs between the cabinets would be fine - but I don't want a "main" portion of LEDs to bridge two cabinets. 

My first thought was to see how many LEDs fit on each section of cabinet, and organize my LED groupings based on a greatest common factor that related all of the required amounts.... Not very fruitful on practicality in the case of my cabinets, which are oddly sized. 

For instance, I have two sections of cabinets that need 16 LEDs and another than needs 78 LEDs.. I plan for these sections to be on one ESP8266.  
16 and 78 have a greatest common factor of 2. 
I could program the entire strip to be operated in sections of 2 pixels - but it wouldn't be efficient with 55 fixtures, using the Hue app, to control three cabinets.. haha!

I haven't really dug into the code yet.. 
I'm assuming there _could_ be a way to state a number of LEDs per light by putting information into an array.. or something..

something along the lines of:
pixelCount[0] = 16;
pixelCount[1] = 16;
pixelCount[2] = 78;

I'm pursuing a degree in computer science - but have only taken 2 classes in the subject matter so far.. I'm very new to coding in general. So I may be totally off the wall here. 

I have found that at many times, "simple problems" can have "complicated solutions."
This may be one of those scenarios.. haha!

Thank you all for your time, and patience with me!

**Comment by mariusmotea** [comment]
This is already present in ring sketch, were there are different number of leds per ring
