### ISSUE TITLE
Any wiring documentation or schemas ?

### ISSUE THREAD

**Issue by idem2lyon** [diyhue/Lights#120]
Hi all, I'm disappointed.
"Select the correct Sketch according to your Harware Setup (e.g. WS2812b)"
That is the only doc available !
Is there a way to get wiring schemas for differents kinds of leds please?

**Comment by mariusmotea** [comment]
Look into Lights repo. You will find there more documentation. For WS2812b (and SK6812) you need to connect strip data pin to RX pin of the board.

https://github.com/diyhue/Lights/tree/master/esp8266-lighting-controllers

<blockquote><img src="https://opengraph.githubassets.com/635d6ce5c6f2058c804e5b03e43f64dfdfbf07adf854f1aae752d1fd9be2c088/diyhue/Lights" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/diyhue/Lights">Lights/esp8266-lighting-controllers at master · diyhue/Lights</a></strong></div><div>DIY lights with support for diyHue. Contribute to diyhue/Lights development by creating an account on GitHub.</div></blockquote>
