### ISSUE TITLE
Entertainment support for FastLED sketches wanted

### ISSUE THREAD

**Issue by Burn-In** [diyhue/Lights#123]
It would be nice to have entertainment mode implemented in the FastLED sketches. I recognized just now that it doesn't exists.
I run a strip with FastLED effects only at the moment and want to combine this code with the Entertainment code. Unfortunately, i haven't the skills to translate the NeoPixelBus code to FastLED.

**Comment by mariusmotea** [comment]
But what benefit will be to switch to FastLED? I use the sketches with NeoPixelBus daily like many other users. No issues at all.

**Comment by Burn-In** [comment]
The only benefit, beside of my own, would be, that the FastLED example sketches have then entertainment support.
