### ISSUE TITLE
sk6812 gradient

### ISSUE THREAD

**Issue by DeLoWaN** [diyhue/Lights#126]
Hi !

As we already have the support of gradient light to ws2812, it would be interesting to have it also on sk6812.

I wanted to also use these strip as main lightning on my room, hence the choice of sk6812 which provides a white LED.

What can be the effort of creating a sketch for this ? Thanks.

**Comment by mariusmotea** [comment]
Hi, the issue is that i'm currently without any SK6812 strip to test. Are you ok to test such sketch? If yes, can you join slack channel to have interactive talk?

**Comment by DeLoWaN** [comment]
Yes sure ! Right now I don't have the hardware since I was reviewing all the solutions that exists to acheive what I want. Gradient would be a great addition though not a must have in my setup, so I will buy the hardware and I let you know when I will have it available for testing.

**Comment by mariusmotea** [comment]
I made an initial release. Please provide me your feedback once you have the hardware. https://github.com/diyhue/Lights/tree/master/ESP8266/Hue_Gradient_Lightstrip_SK6812

<blockquote><img src="https://opengraph.githubassets.com/2d561b700f95277e21a81118b2f88830232678fe7c3d085e8f49913d6a8e96c1/diyhue/Lights" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/diyhue/Lights">Lights/ESP8266/Hue_Gradient_Lightstrip_SK6812 at master · diyhue/Lights</a></strong></div><div>DIY lights with support for diyHue. Contribute to diyhue/Lights development by creating an account on GitHub.</div></blockquote>

**Comment by Mevel** [comment]
@DeLoWaN did you have the chance to test the firmware? 
can you give us some feedback?

**Comment by DeLoWaN** [comment]
@Mevel as discussed with @mariusmotea on [Slack](https://diyhue.slack.com/archives/CC74V7HJL/p1647885324239359), this is working so far.
However, from the Sketch @mariusmotea posted, it still need `NeoSk6812Method` to be replaced by `Neo800KbpsMethod` for this to work properly.

Did not have the chance yet to test it with the Hue App.
