### ISSUE TITLE
Use SK6812 white LED for better color reproduction

### ISSUE THREAD

**Issue by zhuoyang** [diyhue/Lights#127]
Currently it seems like when hue or xy is used, white led is turned off (judging from the code alone), maybe we can use [this method](https://www.dmurph.com/posts/2021/1/cabinet-light-3.html) to convert RGB to RGBW to achieve better color reproduction?
Will try to implement this when my SK6812 arrive.

**Comment by mariusmotea** [comment]
Hi,

It will be great. I did not find a way to take advance of he white led for SK6812 so far.
