### ISSUE TITLE
Generic onoff arduino 

### ISSUE THREAD

**Issue by sommo** [diyhue/Lights#13]
Uploaded to a wemos d1 mini, connected to  a 4relay board, added the esp to the diyhue bridge (with the hue official app) but the realtime status is a mess.. when i try to turn on One of the four output it do it but after few second all the 4 “bulbs “ change state and there is no way to know the real state of them, useless.
I’m doing something wrong?
Also i need to change the logic on how the relay works (inverting the default state in off) because now when i powered it up it starts by turning on all the 4relays

**Comment by Mevel** [comment]
You can modify `Line 45` in the `Setup()` function to set the initial state upon powerup.

`for (uint8_t ch = 0; ch < devicesCount; ch++) {
    pinMode(devicesPins[ch], OUTPUT);
digitalWrite(devicesPins[ch],LOW;
}`

Remark: depending on your Relay Board (active LOW or active HIGH) you need to change the powerstate.

**Comment by sommo** [comment]
Thank you Mavel, i Will flash it again with this Line modified.
What about the major issue? The wemos webpage has only one switch.
Throught the diyhue bridge webpage, i have the four bulb.. but also via webpage controlling bulb doesnt update correctly their status

Inviato da iPhone

**Comment by mariusmotea** [comment]
I will try to replicate this error with an empty wemos. Looking to the code i don't find the problem.

**Comment by sommo** [comment]
Thank you!
Let me know.
I flashed a new wemos d1 mini, all process (flash/wifimanager/add the light via hueapp) went good but it doesnt works like should be.
It seems something wrong on getting its real time status. Once turning on 1 of 4 bulb (via official hue app), all seems ok but after few seconds (about 4 seconds) every bulbs turn to on. this happen in diyhuebridge webpage too while trying to control one bulb too.
Let me know Also if you need log.
The project is amazing!
Matteo

Inviato da iPhone

**Comment by mariusmotea** [comment]
i will need the debug log because i was not able to replicate this. I believe there is an error in the function that fetch the lights status every 15 seconds when hue app is active, so i want to see the error

**Comment by sommo** [comment]
Can you point me on how to get the log?

Inviato da iPhone

**Comment by sommo** [comment]
Here https://diyhue.readthedocs.io/en/latest/AddFuncts/debug.html?highlight=Debug

<blockquote><div><strong><a href="https://diyhue.readthedocs.io/en/latest/AddFuncts/debug.html?highlight=Debug">Enable debug mode — diyHue 1.0 documentation</a></strong></div></blockquote>

**Comment by sommo** [comment]
Really dont know what happend but once tried the debug mode, all works like a charm, so i stopped the debug and launch the systemctl and magically work like it should do.
Only difference i put a dhcp reservation but i cant imagine that was this the problem cause if it fails to connect it will return to wifimanager mode (right?).

Thank you for help me in troubleshooting.. i keep testing anyway.

A question, could i add the hue emulator bridge into homekit ecosystem? If so, How could i do?

Inviato da iPhone

**Comment by sommo** [comment]
Maybe I found a way, throught homebridge and the homebridge-hue plugin. I will let you know so to share with the community

**Comment by mariusmotea** [comment]
Please share your findings with homebridge-hue, lot of people ask about this.

**Comment by sommo** [comment]
I successfully added your diyhue bridge and light to the HomeKit !
I will share soon how to do it step by step

**Comment by sommo** [comment]
> 
> 
> You can modify `Line 45` in the `Setup()` function to set the initial state upon powerup.
> 
> `for (uint8_t ch = 0; ch < devicesCount; ch++) { pinMode(devicesPins[ch], OUTPUT); digitalWrite(devicesPins[ch],LOW; }`
> 
> Remark: depending on your Relay Board (active LOW or active HIGH) you need to change the powerstate.

I tried to modify the sketch to match my relayboard, active high, but i recieve a compile error with your string modified:

Generic_ON_OFF_device_HUE_relayboardinverted:46: error: expected ')' before ';' token

     pinMode(devicesPins[ch], OUTPUT); digitalWrite(devicesPins[ch], LOW;

                                                                        ^

i really don't know how to modify all the sketch to make it works with my relay board...
need to be the opposite of how is build the original sketch..
looking to the sketch, maybe i simple need to change the 2 LOW string to HIGH and viceversa (HIGH to LOW), in line 92/100/134/141, right? maybe this is enough.. Thank you!
p.s. what you said before (changing line 45) is about powerstate recovery (last features of hue), how does it works with this project? does the rpi/arduino store somewhere the light status and set the it on power on?

**Comment by sommo** [comment]
> 
> 
> Please share your findings with homebridge-hue, lot of people ask about this.

Here is how to get diyhue works with homekit:

**1) install homebridge**
**2) install homebridge-hue**
**3) prepare config.json for homebridge with an intial homebridge-hue plugin setup (need to be modified after the first run, see next step):**

config.json initial:
{
	"bridge": {
		"name": "HB_Diy_Hue",
		"username": "mac-address homebridge",
		"port": 51838,
		"pin": "whatyouwant"
	},
	"accessories": [],
	  "platforms": [
    {
      "platform": "Hue",
      "users": {
        "": ""
      },
      "hosts": "put_here_the_ip_diyhue_bridge",
      "sensors": false,
      "nativeHomeKitSensors": true,
      "nativeHomeKitLights": false,
      "excludeSensorTypes": ["Daylight", "CLIP", "Geofence"],
      "lights": true
    }
  ]
}

**4) run home bridge for the first time (not via service) :**
sudo homebridge -U /path that contains config.json (showed before), in my example:
sudo homebridge -U /home/pi/.homediyhue

[2/3/2019, 9:24:33 AM] [Hue] RpiHue: HA-Bridge v1810251352, api v1.24.0
[2/3/2019, 9:24:33 AM] [Hue] RpiHue: bridge request 2: post / {"devicetype":"homebridge-hue#raspberrypi"}
[2/3/2019, 9:24:33 AM] [Hue] RpiHue: bridge error 101: link button not pressed
[2/3/2019, 9:24:33 AM] [Hue] RpiHue: press link button on the bridge to create a user

**5) go to diyhue webpage and simulate the link button pressed (http://{IP_ADDRESS}/hue/linkbutton):**


[2/3/2019, 9:24:48 AM] [Hue] RpiHue: created user - please edit config.json and 

restart homebridge
  "platforms": [
    {
      "platform": "Hue",
      "users": {
        "B827EBFFFE959284": "470a0c52e89555f73b11904c84af6192"
      }
    }
  ]

**6) stop homebridge**
**7) edit config.json with this user**
**8) start homebridge (via service or manually)**


[2/3/2019, 9:24:48 AM] [Hue] RpiHue: 5 accessories
[2/3/2019, 9:24:48 AM] [Hue] masked debug info dumped to /home/pi/.homediyhue/homebridge-hue.json.gz
[2/3/2019, 9:24:48 AM] [Hue] Initializing platform accessory 'RpiHue'...
[2/3/2019, 9:24:48 AM] [Hue] RpiHue: 2 services
[2/3/2019, 9:24:48 AM] [Hue] Initializing platform accessory 'Hue bulb Plug 01'...
[2/3/2019, 9:24:48 AM] [Hue] Initializing platform accessory 'Hue bulb Plug 01 2'...
[2/3/2019, 9:24:48 AM] [Hue] Initializing platform accessory 'Hue bulb Plug 01 3'...
[2/3/2019, 9:24:48 AM] [Hue] Initializing platform accessory 'Hue bulb Plug 01 4'...

**Comment by mariusmotea** [comment]
Thanks, this will go in the wiki

**Comment by sommo** [comment]
thanks to you for the project, glad to contribute!
let me know for what asked before (relay board inverted), so i could test it and maybe could be useful to publish a generic onoff sketch (for relay board inverted-active high/low).
i also bought a strip led rgb (3 pin), to test with your sketch :) it should arrive tomorrow..

**Comment by ghost** [comment]
Added home kit instructions [here](https://diyhue.readthedocs.io/en/latest/AddFuncts/homekit.html). Would you mind checking them to make sure I formatted it all correctly @sommo !?

**Comment by sommo** [comment]
> 
> 
> Added home kit instructions [here](https://diyhue.readthedocs.io/en/latest/AddFuncts/homekit.html). Would you mind checking them to make sure I formatted it all correctly @sommo !?

that's ok!

**Comment by sommo** [comment]
Hope someone could help me to modifiy the sketch (arduino generic onoff) to let it work with a relayboard active high.....

**Comment by Mevel** [comment]
there is a typo: missing a `) `

You can join our slack group for help

Https://joinslack.diyhue.org

You can contact me there for live debugging and we will post the result here.

**Comment by sommo** [comment]
i joined the slack group and asked for that (sketch arduino generico onoff for relay board active high)

**Comment by sommo** [comment]
> 
> 
> there is a typo: missing a `) `
> 
> You can join our slack group for help
> 
> [Https://joinslack.diyhue.org](Https://joinslack.diyhue.org)
> 
> You can contact me there for live debugging and we will post the result here.

so only changed this will make the sketch working for a relayboard active high?

void setup() {
  EEPROM.begin(512);

  for (uint8_t ch = 0; ch < devicesCount; ch++) {
    pinMode(devicesPins[ch], OUTPUT); digitalWrite(devicesPins[ch], LOW);
  }
