### ISSUE TITLE
What Type is Yeelight LED strip?

### ISSUE THREAD

**Issue by julianCast** [diyhue/Lights#132]
Hi, what chip would be for the yeelight led strips in this list?
Can anyone explain how to use that page? I flash the sd card with it?

Thanks!
![image](https://user-images.githubusercontent.com/559677/193073836-914cdebc-8698-4544-9015-c88eb0de2850.png)

**Comment by Mevel** [comment]
You can build a inexpensive led strip with esp8266 microcontroller like nodemcu or wemos d1 etc.

https://diyhue.org/lights/diylight-build-your-own-smart-light/

According to your attached hardware you select the sketch and flash.

Easiest would be ws2812 strips with generic or gradient firmware emulating the gradient strip of original hue. Saving a lot of money!

Sidenote: the website is under development for the next hours, expect some errors, as we update it for future esp32 firmware. 

<blockquote><img src="https://diyhue.org/wp-content/uploads/2022/05/mcu-wiring-01-1024x500.png" width="48" align="right"><div><img src="https://diyhue.org/wp-content/uploads/2019/11/cropped-Zeichenfläche-4-1-192x192.png" height="14"> diyHue</div><div><strong><a href="https://diyhue.org/lights/diylight-build-your-own-smart-light/">diyLight - build your own smart Light with diyHue</a></strong></div><div>Find all infos about our diyLight - build your own smart Light with just a few parts. Gradient Strips, Ambient light etc controlled by diyHue</div></blockquote>

**Comment by julianCast** [comment]
Thank you! I'll close the issue. Good work.
