### ISSUE TITLE
Change LED Pin

### ISSUE THREAD

**Issue by Scarala** [diyhue/Lights#134]
I have 10 Wemos D1 mini with WS2812 Led strips that i want to use with diyHUE.

Problem is: They were designed for the old diyhue version and the DATA-Pin on every wemos is on D2.
In the meantime I used them (the last two years) with another firmware to control them via a DMX software over ArtNET.

Now i wanted to switch to the new diyHUE but sadly there is no configuration for the LED data pin anymore.
I really dont want to disassamble all my lights and enclosures to resolder all the strips to RX.

Is there any chance to tell the Genereic WS2812 Strip sketch to use D2(GPIO4) for the data pin?

**Comment by mariusmotea** [comment]
Hi,
I already replied on Slack, the NeopixelBus library use some hardware features that work only on RX pin, so unfortunately it cannot be changed.

**Comment by Scarala** [comment]
Unfortunately i got it working myself. I am using generic WS2812B-LED-Strips and i just replaced the NeoPixelBus-Method with NeoEsp8266BitBangWs2812xMethod so i can specify the pin in the "strip = new NeoPixelBus"-Line.
Old Lines:
1.`NeoPixelBus<NeoGrbFeature, Neo800KbpsMethod>* strip = NULL;`
2.`strip = new NeoPixelBus<NeoGrbFeature, Neo800KbpsMethod>(newCount);`
New lines:
1.`NeoPixelBus<NeoGrbFeature, NeoEsp8266BitBangWs2812xMethod>* strip = NULL;`
2.`strip = new NeoPixelBus<NeoGrbFeature, NeoEsp8266BitBangWs2812xMethod>(newCount,4);`
Works well for me
