### ISSUE TITLE
Samsung TV Hue Sync App not working

### ISSUE THREAD

**Issue by ministryofsillywalks** [diyhue/Lights#140]
I have a Samsung TV and a few months ago an app for the TV was released to allow the syncing of hue lights.
https://www.philips-hue.com/en-us/explore-hue/propositions/entertainment/sync-with-tv/sync-app
Its 129€ which is crazy, but I thought I'd try it out as there is a 14 day refund window.

The samsung tv app finds the diyhue bridge.
Pairing works.
The entertainment zone is selectable on the tv app.
However the lights don't light up and don't sync to the tv.
Using the same bridge and light I can sync up with the hue sync app on windows just fine.

Is there any debugging I can do to try and dig into this why the samsung app doesn't seem to work?

My setup:
Latest stable diyhue bridge running in docker
WS2812b running with a wemos d1 mini with the ws2812 gradient strip frimware (defined as lcx002 inside diyhue)

Like I said the setup works fine with the PC app but not the samsung app.
Happy to try out everything.

**Comment by ministryofsillywalks** [comment]
Doesn't belong in lights.
Issue in the main repo
https://github.com/diyhue/diyHue/issues/898

**Comment by mariusmotea** [comment]
We are debugging now on Slack similar issue.
