### ISSUE TITLE
Self-compiled sketches == reset loop

### ISSUE THREAD

**Issue by lukeIam** [diyhue/Lights#144]
Hi,

I have a SK6812 led stripe and an esp8266 (D1 Mini) and I want to use it in hue entertainment.
So I'm trying to compile this: (as there seems to be no binaries for  SK6812_gradient):
https://github.com/diyhue/Lights/blob/master/ESP8266/Hue_Gradient_Lightstrip_SK6812/Hue_Gradient_Lightstrip_SK6812.ino

Compiling is not the problem (succeeds without errors) but when I flashed it to the esp8266 I get into a reset loop.
I also tried the same with an ESP32 -> same problem (with the esp32 sketch).

If I flash over the website it works fine (but no gradient available).

Any idea?

**Comment by mariusmotea** [comment]
Hi,

What libraries do you use? Probably one is wrong.

**Comment by lukeIam** [comment]
> What libraries do you use? Probably one is wrong.

Most likely - I played around with different versions but no success (is there an official list with the correct versions?)
I'm currently using:
![image](https://github.com/diyhue/Lights/assets/5115160/a576b063-d95f-4a31-8fad-ffbf81c25954)

Edit: Board lib:
![image](https://github.com/diyhue/Lights/assets/5115160/e50bc8a6-dcfb-4eba-bea0-26e2c362a9ca)

Compiling works fine...

**Comment by mariusmotea** [comment]
Have you flashed with SPIFFS partition to allow creation of config file?

**Comment by lukeIam** [comment]
Yes - followed the instructions I found somewhere here in the repo.

EDIT: 4M (3M SPIFFS)

BTW: is there a technical limitation that your web flasher only supports some sketches?

**Comment by lukeIam** [comment]
this is what I get via serial:
```
��n�r��n|�l�l`bbrl�nb�nl`�rl�l��
 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x4010f000, len 3424, room 16 
tail 0
chksum 0x2e
load 0x3fff20b8, len 40, room 8 
tail 0
chksum 0x2b
csum 0x2b
v0006a580
~ld
```

**Comment by lukeIam** [comment]
It looks like with the flash size option: `Mapping defined by Hardware and Sketch` it's working ^^

Edit: ok flashing works, the web interface comes up, wifi configured but as soon as I set any settings in the webui -> reset with the same error
(currently thinking if I may got a clone with less memory...)

Using WLED now
