### ISSUE TITLE
Change Color Order

### ISSUE THREAD

**Issue by cscherpenisse** [diyhue/Lights#148]
I have an LED strip that looks like the WS2812B.
This works with the WS2812_STRIP v3.1 on a Wemos D1 mini.
Only the colors do not match, red=blue, blue=green and green=red.
Is it possible to change the color order from, for example, RGB to GRB?

**Comment by hendriksen-mark** [comment]
You can change to order by changing these 2 lines.
Rgb or grb or bgr or what you need.

https://github.com/diyhue/Lights/blob/master/ESP8266%2FGeneric_WS2812_Strip%2FGeneric_WS2812_Strip.ino#L64

https://github.com/diyhue/Lights/blob/master/ESP8266%2FGeneric_WS2812_Strip%2FGeneric_WS2812_Strip.ino#L568

Its not possible to change it after flashing.

**Comment by cscherpenisse** [comment]
Thanks for your instruction, it works now.

**Comment by cscherpenisse** [comment]
-
