### ISSUE TITLE
Generic_SK6812_Strip: RGB colors multipliers not working

### ISSUE THREAD

**Issue by 350d** [diyhue/Lights#154]
Hello! I've just switched from WS2812 to SK6812 strip and noticed that RGB multipliers can't be used.
All code related to `rgb_multiplier` are missed from sketch. I've added [pull request](https://github.com/diyhue/Lights/pull/155) already.

**Comment by hendriksen-mark** [comment]
Hi, thanks for the fix.

**Comment by 350d** [comment]
@hendriksen-mark Do I need to push compiled version for https://install.diyhue.org or it will be available to install automatically?

<blockquote><div><strong><a href="https://install.diyhue.org/">diyHue Flash Tool</a></strong></div></blockquote>

**Comment by mariusmotea** [comment]
The automatic build was turned off since the builded firmware was not working at all. If you can also replace the binary file it will be great.

**Comment by hendriksen-mark** [comment]
Please use the new version on github and not your local version, there have been 2 updates to the sketch.

**Comment by 350d** [comment]
@mariusmotea @hendriksen-mark Thank you for information. Compiled, tested, committed!
