### ISSUE TITLE
Arduino OTA not working, cannot change led count

### ISSUE THREAD

**Issue by oleg2204** [diyhue/Lights#24]
The Arduino OTA is not finding my SK6812 Lightstrip anymore. So i need to hook up the nodemcu directly to the computer again.
Also if i change any variable like ledcount, the change gets ignored (cause it loads the settings from the json, how do i delete the setting store?)

**Comment by mariusmotea** [comment]
Access light web interface -> settings

**Comment by oleg2204** [comment]
Ah okay nice. That did work. But how i do the ota update stuff?

**Comment by mariusmotea** [comment]
Will be directly from bridge. Now you can pick the firmware compiled in bin folder and uploade it to light with browser on /update path.
