### ISSUE TITLE
New feature: Using fixed point maths instead of floating point maths

### ISSUE THREAD

**Issue by Pantastisch** [diyhue/Lights#25]
To speed up the calculations, considering to do fixed point maths instead of floating-point maths shall be thought off.

I could do that, if the commitment from the project host is okay.

**Comment by mariusmotea** [comment]
Saying this, probably you know much better C/C++ than us, so please show us how to improve the lights. Most commits in lights are made by me and i'm not a programmer, this is just hobby...

**Comment by Pantastisch** [comment]
@mariusmotea  Okay, I will do some optimization

**Comment by ghost** [comment]
@mariusmotea @Pantastisch I'm going to close this as you seem to be working on it @Pantastisch Feel free to open a PR when you have something ready
