### ISSUE TITLE
 WS2812BHueStrip:6:25: error: NeoPixelBus.h: No such file or directory

### ISSUE THREAD

**Issue by charlescbullock** [diyhue/Lights#4]
Hey, so I've tried to upload the .ino file, "WS2812BHueStrip.ino" and it gives me the error in the title.

What am I doing wrong?

I am connected to the ESP8266 via usb.
I am in the arduino IDE using com14, as the device is directly connected via USB... as opposed to a USB-UART device.. 

I have those too.. 

This is the ESP8266 unit I am using.
https://www.amazon.com/gp/product/B010N1SPRK/ref=ppx_yo_dt_b_asin_title_o03__o00_s00?ie=UTF8&psc=1

Thanks!!

**Comment by mariusmotea** [comment]
In arduino enter in library manager and look for NeoPixelBus by Makuna library. Install that and you will not receive this error anymore.

**Comment by charlescbullock** [comment]
Got it. 

Thank you!!!!
