### ISSUE TITLE
ESP8266 Library Version?

### ISSUE THREAD

**Issue by ryancasler** [diyhue/Lights#49]
I don't see anything listed about which version of the esp8266 library we should be using when building sketches for DIY lights.  If there is a recommendation or a non-recommended version, I think it would be helpful to list.  Even it if it is just what version it was developed on, it would be helpful in debugging purposes.  Thanks!!!  Love the project, keep up the very excellent and very appreciated work!

**Comment by mariusmotea** [comment]
I don't test it with last release but i can confirm that version 2.4.2 is working fine.
