### ISSUE TITLE
Right operand of comma operator has no effect

### ISSUE THREAD

**Issue by vhsw** [diyhue/Lights#51]
Strange piece of code at:
https://github.com/diyhue/Lights/blob/master/Arduino/Generic_RGB_CCT_Light/Generic_RGB_CCT_Light.ino#L63

```C
hh = light.hue;
if (hh >= 65535.0) hh = 0.0;
hh /= 11850, 0; // <-  this
```
Maybe it's should be `hh /= 11850.0;` or `hh /= 11850;`?

**Comment by mariusmotea** [comment]
I believe it must be float so 11850.0
I will check and fix, thanks.
