### ISSUE TITLE
Multiplier has to be at least 1 to get a light.

### ISSUE THREAD

**Issue by Fisico** [diyhue/Lights#53]
After flashing my wemos to light version 3.0 with the ws2812b sketch, I had to set the red, green and blue multiplier to at least 1 to get any light out of the strip and to 100 to get full brightness. Shouldn’t this be default values, set in the code?

**Comment by mariusmotea** [comment]
Default are 100, but in case of upgrade it is not working. I will look for a fix to this bug.

**Comment by mcer12** [comment]
When you make an OTA update or update without complete memory wipe, your old saved config file stays intact. There is no check if json contains the values, that means if new values are added in an update like the multiplier, it is undefined.

**Comment by Fisico** [comment]
I tested it and after a wiping the flash and reflashing the v3 firmware the multiplier value is 100 so this is not a problem than.
Should I close the issue?

**Comment by Fisico** [comment]
fixed with https://github.com/diyhue/Lights/commit/0462e7f7c3529f681b70b65a6d5fc1c4b7227cda
