### ISSUE TITLE
generic-rgbw-light sketch fails to start server

### ISSUE THREAD

**Issue by vKnmnn** [diyhue/Lights#55]
Hi all,

i recently bought some MagicHome RGBW controllers and before flashing i updated to the latest master in git. now these lamps do not start any sort of webserver which could be used to set the Wifi. When the wifi-information is already set, the device successfully connects to wifi and responds to ICMP ping, but otherwise is unavailable.

**Comment by mariusmotea** [comment]
You are using latest libraries for esp8266 and wifi manager?

**Comment by vKnmnn** [comment]
esp8266_mdns v1.1.7
WiFiManager v0.14.0
ArduinoJson v6.12.0

Those are the libs i'm using.
notably, the chip in MagicHome controllers is a ESP8285, but afaik that shouldn't make much of a difference

**Comment by mariusmotea** [comment]
May be a problem because you need SPIFFS partition. Try to flash it using 1M 512KB SPIFFS. Board must be Generic ESP8285 chip
