### ISSUE TITLE
RGBW Hue Ring?

### ISSUE THREAD

**Issue by robotica72** [diyhue/Lights#57]
Any chance someone could add the FW that changes the original Hue Ring code from RGB to RGBW?

**Comment by mariusmotea** [comment]
This is very easy to do, just add the 4th channel in the sketch, but be aware that ring sketch is not updated and miss some new futures.

**Comment by robotica72** [comment]
Thanks - I thought it was more complex than just adding the 4th channel.   Are there any planne updates to the Ring code for the newer features?    I havent looked at any other code yet - so I may be able to use something else for my projects.

**Comment by mariusmotea** [comment]
Is complicated to upgrade this sketch because in new version all settings need to be migrated in the web gui and stored in SPIFFS.
