### ISSUE TITLE
Light Support WS2811

### ISSUE THREAD

**Issue by rammstone83** [diyhue/Lights#59]
Hi is there still the possibility to use WS2811 Strips with an ESP8266(nodemcu), Thanks in advance for the help

**Comment by mariusmotea** [comment]
Yes, only a minor change is needed. I think two colors are reversed compared to ws2812 and it can be fixed in library definition, instead of grb must be gbr or something else.

`NeoPixelBus<NeoGrbFeature, Neo800KbpsMethod>* strip = NULL;`

**Comment by charlescbullock** [comment]
Do you edit this on the library file: "NeoPixelBus.h" or in the Arduino file for the ESP8266?

Thanks!
