### ISSUE TITLE
Support Ws2818

### ISSUE THREAD

**Issue by Xorfee** [diyhue/Lights#67]
Is there anyway to support ws2818?

**Comment by mariusmotea** [comment]
This is more an issue for https://github.com/Makuna/NeoPixelBus. If the support will be added in the library then it will work probably with ws2812 sketch.

<blockquote><img src="https://avatars2.githubusercontent.com/u/7972357?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/Makuna/NeoPixelBus">Makuna/NeoPixelBus</a></strong></div><div>Adafruit enhanced NeoPixel support library. Contribute to Makuna/NeoPixelBus development by creating an account on GitHub.</div></blockquote>
