### ISSUE TITLE
Cannot open Webinterface with Generic_RGB_Light

### ISSUE THREAD

**Issue by Gaming12846** [diyhue/Lights#71]
I set up the Generic_RGB_Light and connected to the wifi, but when I try to open the web interface I get a timeout and my Hue emulator cannot find the RGB stripe.

**Comment by Mevel** [comment]
Could you try a different sketch and see if the problem persists? Do you use static ip or DHCP?

**Comment by Gaming12846** [comment]
Other Stetches like Generic_WS2812_Strip working perfectly, i can open the webinterface and the hue app detects the Light. I use DHCP on the Sketch and set a static ip in my Fritz Box. Its work fine for  	Generic_WS2812_Strip.

**Comment by Gaming12846** [comment]
I solved it, i switched to esp8266 version 2.4.1 with these settings:

    Set the CPU frequency to 80 MHz
    Set the Flash Size to "4M (1M SPIFFS)". <-- Double check this!
    Set the upload speed to 115200 (you could try to set it higher, but it could cause problems).
    Set "IwIP Variant" to "v2 Higher Bandwidth".
