### ISSUE TITLE
ESP8266 cannot be found?

### ISSUE THREAD

**Issue by mmaxus35** [diyhue/Lights#73]
Dear All,
I have successfully created my RP3 bridge using; 
curl -s https://raw.githubusercontent.com/diyhue/diyHue/master/BridgeEmulator/easy_install.sh | sudo bash /dev/stdin 
sudo systemctl [start/stop/restart] hue-emulator.service

- The nmap is installed in RP3.
- The service successfully runs and I could activate my bridge and pair with the Hue App.
- I successfully built the WS2812 ino file in Arduino IDE and flashed to ESP8266.
- ESP8266 connected my home network.

However, The app does not find the ESP8266 as a light. I could not understand the problem.

**Comment by mariusmotea** [comment]
Are you able to ping the ESP8266 from RP3 ? Is the latency less than 10ms? Try to perform light scanning while you ping the ESP8266 as the chip will not be in low power state because of the ongoing ping ICMP traffic.
