### ISSUE TITLE
Use WS2812b on esp32

### ISSUE THREAD

**Issue by dustinh8080** [diyhue/Lights#77]
Is it possible to run the "Light" sketches on an esp32 with *12b neopixels?
I've tried it, but the libs are different to esp8266.
Thanks for any replies.

**Comment by mariusmotea** [comment]
I think you need minimal modifications for esp32 to work. First some libraries names are different (aka: webserver), then you need to read neopixelbus library modification for esp32 (if any).

**Comment by dustinh8080** [comment]
My second try was with the "ESP32_SK9822_FastLED_Strip"-Script
after several library installations ive fixed the ESP32 implementation.
I also modified lines 95 and 97, same code but without Clock-Pin, as is use 3 Pin ws2812b with GND DATA VCC. But it shows me the error:
`'HueApi' does not name a type`

What would be your suggestion? Should i go on with the ESP32_SK9822 script, or with the ESP8266_WS2812B script?

**Comment by mariusmotea** [comment]
Maybe https://github.com/linuzer can help you as he develope the code for esp32

<blockquote><img src="https://avatars1.githubusercontent.com/u/3530673?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/linuzer">linuzer - Overview</a></strong></div><div>linuzer has 5 repositories available. Follow their code on GitHub.</div></blockquote>
