### ISSUE TITLE
ESPHome only compiles as RGBW

### ISSUE THREAD

**Issue by jannislehmann** [diyhue/Lights#83]
When trying to create an only RGB configuration, the compilation fails, because this line
https://github.com/diyhue/Lights/blob/master/ESPHome/AsyncUDP/diyhueasyncudp.h#L26 (in all three files) requires a white_led to be returned. However, this is not the case.

Therefore, a check should be add to check whether a white_led exists.
I haven't really worked with C++ but I might try this myself next week.

**Comment by mariusmotea** [comment]
Did you test also with older wled library? Can you post the versions of libraries you are using?

**Comment by jannislehmann** [comment]
I didn't use wled at all?

**Comment by mariusmotea** [comment]
sorry, i was looking to your code and i misread  white_led as wled. Anyway i can test to compile on my laptop if you provide me your libraries versions.

**Comment by jannislehmann** [comment]
I simply cloned the repo.
And then try to remove the `white_led` from the esphome yaml.
If you look at the linked code above, you will see that this cannot work and will throw an error.

**Comment by jannislehmann** [comment]
I did some testing and realized there is no way to check whether the light exists.
Therefore, I guess, the best would be to just duplicate the header files. One for RGB and one for RGBW, which contains the `white_led`.

Another way would be to declare a global variable, which points to the `white_led` on `on_boot` if set. This way, one could check whether a `white_led` is `NULL`

**Comment by jannislehmann** [comment]
Not stale.
