### ISSUE TITLE
Generic_WS2812_Strip WebInterface broken

### ISSUE THREAD

**Issue by cyptus** [diyhue/Lights#89]
The webinterface of `Generic_WS2812_Strip` script serves contents from `https` sites which does not work as the webinterface it self is only served by `http` (`mixed content`).
Especially contents of `https://raw.githubusercontent.com` are not allowed, as github serves them with response content type `plain/text` which is not accepeted by modern browsers for scripts or css.

Also i am not sure if the webinterface itself works like expected, as there are no values loaded and i did break the code twice by entering values and pressing save (boot loop after config load). I needed to clear flash storage afterwards.

**Comment by Mevel** [comment]
This might be introduced due to #84 @dobby5 @alexyao2015

**Comment by mariusmotea** [comment]
A public CDN set the mime type for hosted files, while github not. We need to swith to a public CDN

**Comment by mariusmotea** [comment]
I just made the switch to diyhue.org CDN
