### ISSUE TITLE
Can't flash on NodeMCU

### ISSUE THREAD

**Issue by kompas1** [diyhue/Lights#90]
Okay so I can't flash the Generic_RGB.ino or the Ws2812 script because there is missing the FS.h file. Anybody knows where to get it or what exactly is missing that it's not working. Have the ESP32 Board file from arduino installed but still can't get it to work

**Comment by Mevel** [comment]
If I am not mistaken, nodemcu is esp8266 based board, you need to install the board library from support library within arduino IDE.

**Comment by kompas1** [comment]
okay so I changed the board to every node version that the board manager has, as well as the generic ESP8266 module. I am not getting the error of the missing FS.h but now I am stuck with the missing WiFiManager.h

**Comment by mariusmotea** [comment]
Install WiFi Manager library by tzapu

**Comment by kompas1** [comment]
Oh dang it. I did it and i could compile easily. Now I just somehow have to figure out the connections to the rgb led
okay got it after some fidling around. Will close this thread now
