### ISSUE TITLE
NodeMCU WS2812 won't show up

### ISSUE THREAD

**Issue by kompas1** [diyhue/Lights#91]
So I flashed the Generic_WS2812 with all customizations that needed to be done (the Pixel-count only) and I could flash it successfully. When I power the whole thing up i get a, some sort of "boot-animation" but if i try to connect to the hotspot of the node I can't because it didn't get shown even after 10 Minutes no sight of the hotspot. Has anyone had a similar problem?

**Comment by mariusmotea** [comment]
Did you flash is with spiffs storage?

**Comment by kompas1** [comment]
I've setup the Flash Size to 4MB(FS: 3MB) do you mean that? Or is there somewhere an other option i've not seen somehow

edit: so i got it working, at least on one node, the problem is i can't get it to work on a second node, couldn't turn on the LED Strip though. but i could run other codes without any problems, so it kinda messes me up that i can't get the generic_ws2812 script to work

**Comment by kompas1** [comment]
so after a lot of sleepless nights and a lot of fiddeling around i got it to work. Now I just have to connect it to the diyHue Bridge and everything is fine
